### ISSUE TITLE
Remember that a set is a *mathematical* set has a built in bug

### ISSUE THREAD

**Issue by ShaheensWeb** [lazerwalker/clojurescript-koans#14]
Not sure if this is a real issue just realized this upon using clojurescriptkoans as a way to prep for my upcoming employment.

By definition in the REPL: a set #{ 1 1 2 3} logs an error about duplicate 1 keys, makes sense right?
<img width="1033" alt="screen shot 2016-01-21 at 1 46 08 pm" src="https://cloud.githubusercontent.com/assets/3826375/12490789/58a07a86-c045-11e5-94c7-2684ea7dbd83.png">

But the above koan seems to accept a set with duplicates as if it was correct. I wouldn't mind working in the fix myself, would love to be a contributor to such a cool technological way to educate people!

**Comment by lazerwalker** [comment]
Out of curiosity, what REPL are you using? 

Evaluating  `(set '(1 1 2 2 3 3 4 4 5 5))` or `#{1 1 1 2 2 2 3 3 3 4 4 4 5 5}` in the http://clojurescript.net REPL results in `#{1 2 3 4 5}` for both; it seems to me that the expected behavior for trying to create a set with duplicate keys is to return a proper mathematical set with keys deduplicated.

**Comment by NickCorneau** [comment]
I believe Shaheen is using the Cider REPL. I'm experiencing the same issues as he is using a Cider REPL.

When evaluating ```(= #{1 1 2 3} (set '(1 1 2 3)))``` I get the result ```IllegalArgumentException Duplicate key: 1```

**Comment by ShaheensWeb** [comment]
Following a guide from Braveclojure developing in EMACS primarily. In terms of versions refer to both photos below (I'm on my first week of Clojure, but it seems to be a clojurescript repl vs clojure repl issue). 
<img width="665" alt="screen shot 2016-01-21 at 1 54 05 pm" src="https://cloud.githubusercontent.com/assets/3826375/12491042/d08dcc96-c046-11e5-9f64-25326b4a12d4.png">
<img width="677" alt="screen shot 2016-01-21 at 1 55 02 pm" src="https://cloud.githubusercontent.com/assets/3826375/12491056/dd0acc62-c046-11e5-820e-3548b8cc3375.png">

**Comment by lazerwalker** [comment]
Hmm, curious!

The [Clojure docs for the "set" function](https://clojuredocs.org/clojure.core/set) implies that  `#{1 1 2 3}` should yield `#{1 2 3}` rather than an `IllegalArgumentException`. I feel pretty comfortable saying, then, that the Koans are working as expected.

Presumably that'd apply to both Clojure and CLJS – maybe worth opening an issue in CIDER? Now I'm super-curious to find out what's going on!

**Comment by lazerwalker** [comment]
Er, I clearly spoke to soon. `(set '(1 1 2 3))` should equal `#{1 2 3}` (and it does at http://www.tryclj.com), but `#{1 1 2 3}` does yield that error in that REPL. 

My suspicion is you're right and it's a Clojure vs ClojureScript thing.

**Comment by ShaheensWeb** [comment]
@lazerwalker makes sense. Thanks for the fast responses. I guess this is not a bug though because the domain is "clojurescriptkoans", not "clojurekoans" :+1:

**Comment by NickCorneau** [comment]
@lazerwalker Thank you for the response. @ShaheensWeb I'm curious as to why the literal #{val1 val2 ...} operates differently than (set '(1 1 1 2 3)) in Clojure as opposed to ClojureScript. Time for some digging!

**Comment by lazerwalker** [comment]
Going to close this for now, but I'd love to hear if you find anything interesting, @NickCorneau!
