### ISSUE TITLE
higher-order-functions #10 accepts wrong answers

### ISSUE THREAD

**Issue by fugalfunkster** [lazerwalker/clojurescript-koans#22]
I was able to pass through with just about any input. For example: the keyword :inconcievable is acceptable, but: a b - which I presume is the answer - is not).

**Comment by mkremins** [comment]
This seems to be because `(< foo)` always returns `true` for any value of `foo`, so any single-form answer will cause the anonymous function in the koan to return its second argument. This then causes the whole `reduce` expression to return `"longest"`, since `"longest"` is the last item in the vector of words.

This could be fixed by adding a shorter word or two to the vector after `"longest"`, or perhaps by splitting the input up into two adjacent inputs so that the user is forced to provide `<` with two arguments.
